server:
  port: 9096

spring:
  profiles:
    active: aws

  sql:
    init:
      mode: always
      platform: postgres
      encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    format-sql: true
