server:
  port: 9096

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://localhost:5432/st_roma
    username: euroma
    password: 1111
  sql:
    init:
      mode: always
      platform: postgres
      encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    format-sql: true
