server:
  port: 9096

spring:
#  profiles:
#    active: aws
#    include: oauth
  sql:
    init:
      mode: always
      platform: postgres
      encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    format-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/roma
    username: roman
    password: 1234
    driver-class-name: org.postgresql.Driver

